import { v4 as uuidv4 } from "uuid";
const Songbank = [
    {
      name: "Beaver Creek",
      cover: "assets/jazzband.jpg",
      artist: "Aso, Middle School, Aviino",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10075",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: true,
    },
    {
      name: "Daylight",
      cover: "assets/jazzband.jpg",
      artist: "Aiguille",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9272",
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Keep Going",
      cover: "assets/jazzband.jpg",
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9222",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Nightfall",
      cover: "assets/jazzband.jpg",
      artist: "Aiguille",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9148",
      color: ["#EF8EA9", "#ab417f"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Reflection",
      cover: "assets/jazzband.jpg",
      artist: "Swørn",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9228",
      color: ["#CD607D", "#c94043"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Under the City Stars",
      cover: "assets/jazzband.jpg",
      artist: "Aso, Middle School, Aviino",
      audio: "https://mp3.chillhop.com/serve.php/?mp3=10074",
      color: ["#205950", "#2ab3bf"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Drive",
      cover: "assets/goatunder.png",
      artist: "Funky Apricot",
      album: "The autumn goat undercover",
      audio: "assets/drive7.mp3",
      color: ["#fce4b8", "#e99f56"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Inside",
      cover: "assets/goatunder.png",
      artist: "Funky Apricot",
      album: "The autumn goat undercover",
      audio: "assets/inside.mp3",
      color: ["#fce4b8", "#e99f56"],
      id: uuidv4(),
      active: false,
    },
    {
      name: "Metal",
      cover: "assets/goatunder.png",
      artist: "Funky Apricot",
      album: "The autumn goat undercover",
      audio: "assets/metal.mp3",
      color: ["#fce4b8", "#e99f56"],
      id: uuidv4(),
      active: false,
    },
  ];


export default Songbank;
